import os

Import("env")

dst = 'besavager'

srcs = env.Glob('*.cpp')
libs = ['be']
lib_path = os.getenv('LIBRARY_PATH').split(':')
inc_path = '../'

dst_shared = env.SharedLibrary(target=dst, source=srcs, LIBS=libs, LIBPATH=lib_path, CPPPATH=inc_path)
dst_static = env.StaticLibrary(target=dst, source=srcs, LIBS=libs, LIBPATH=lib_path, CPPPATH=inc_path)

Return("dst_shared", "dst_static")
