import os

env = Environment()

dst = 'besavager'

srcs = Glob('*.cpp')
libs = ['be']
lib_path = os.getenv('LIBRARY_PATH').split(':')
inc_path = os.getenv('BEINCLUDES').split(';')+['../']

env.SharedLibrary(target=dst, source=srcs, LIBS=libs, LIBPATH=lib_path, CPPPATH=inc_path)
env.StaticLibrary(target=dst, source=srcs, LIBS=libs, LIBPATH=lib_path, CPPPATH=inc_path)
