import os

dst = BeCJK'
dst_name = '/boot/system/add-ons/input_server/methods/BeCJK'

srcs = Glob('*.cpp')
libs = ['be', 'besavager']
lib_path = os.getenv('LIBRARY_PATH').split(':') + ['../besavager']
inc_path = os.getenv('BEINCLUDES').split(';')+['../']

env = Environment()
dst_shared = env.SharedLibrary(target=dst, source=srcs, LIBS=libs, LIBPATH=lib_path, CPPPATH=inc_path)

env.InstallAs(dst_name, dst_shared);